export const COURTS = [
  { value: "civilc", label: "ศาลแพ่ง" },
  { value: "civilbsc", label: "ศาลแพ่งกรุงเทพใต้" },
  { value: "civiltbc", label: "ศาลแพ่งธนบุรี" },
  { value: "crimc", label: "ศาลอาญา" },
  { value: "crimsb", label: "ศาลอาญากรุงเทพใต้" },
  { value: "crimtbc", label: "ศาลอาญาธนบุรี" },
  { value: "taxc", label: "ศาลภาษีอากรกลาง" },
  { value: "lbc", label: "ศาลแรงงานกลาง" },
  { value: "jvnc", label: "ศาลเยาวชนและครอบครัวกลาง" },
  { value: "ipitc", label: "ศาลทรัพย์สินทางปัญญาและการค้าระหว่างประเทศกลาง" },
  { value: "cbc", label: "ศาลล้มละลายกลาง" },
  { value: "jor1", label: "สำนักงานอธิบดีผู้พิพากษาภาค 1" },
  { value: "bknmc", label: "ศาลแขวงพระนครเหนือ" },
  { value: "bksmc", label: "ศาลแขวงพระนครใต้" },
  { value: "tbmc", label: "ศาลแขวงธนบุรี" },
  { value: "dsmc", label: "ศาลแขวงดุสิต" },
  { value: "ptwmc", label: "ศาลแขวงปทุมวัน" },
  { value: "atyc", label: "ศาลจังหวัดพระนครศรีอยุธยา" },
  { value: "atymc", label: "ศาลแขวงพระนครศรีอยุธยา" },
  { value: "atyjc", label: "ศาลเยาวชนและครอบครัวจังหวัดพระนครศรีอยุธยา" },
  { value: "lbrc", label: "ศาลจังหวัดลพบุรี" },
  { value: "lbrjc", label: "ศาลเยาวชนและครอบครัวจังหวัดลพบุรี" },
  { value: "lbrmc", label: "ศาลแขวงลพบุรี" },
  { value: "cntc", label: "ศาลจังหวัดชัยนาท" },
  { value: "cntjc", label: "ศาลเยาวชนและครอบครัวจังหวัดชัยนาท" },
  { value: "snbc", label: "ศาลจังหวัดสิงห์บุรี" },
  { value: "snbjc", label: "ศาลเยาวชนและครอบครัวจังหวัดสิงห์บุรี" },
  { value: "srbc", label: "ศาลจังหวัดสระบุรี" },
  { value: "srbjc", label: "ศาลเยาวชนและครอบครัวจังหวัดสระบุรี" },
  { value: "antc", label: "ศาลจังหวัดอ่างทอง" },
  { value: "antjc", label: "ศาลเยาวชนและครอบครัวจังหวัดอ่างทอง" },
  { value: "pttc", label: "ศาลจังหวัดปทุมธานี" },
  { value: "pttjc", label: "ศาลเยาวชนและครอบครัวจังหวัดปทุมธานี" },
  { value: "tybc", label: "ศาลจังหวัดธัญบุรี" },
  { value: "ntbc", label: "ศาลจังหวัดนนทบุรี" },
  { value: "ntbmc", label: "ศาลแขวงนนทบุรี" },
  { value: "ntbjc", label: "ศาลเยาวชนและครอบครัวจังหวัดนนทบุรี" },
  { value: "smpc", label: "ศาลจังหวัดสมุทรปราการ" },
  { value: "smpmc", label: "ศาลแขวงสมุทรปราการ" },
  { value: "smpjc", label: "ศาลเยาวชนและครอบครัวจังหวัดสมุทรปราการ" },
  { value: "cbdc", label: "ศาลจังหวัดชัยบาดาล" },
  { value: "lblbrc", label: "ศาลแรงงานภาค 1 (สระบุรี)" },
  { value: "jor2", label: "สำนักงานอธิบดีผู้พิพากษาภาค 2" },
  { value: "cnbc", label: "ศาลจังหวัดชลบุรี" },
  { value: "cnbmc", label: "ศาลแขวงชลบุรี" },
  { value: "cnbjc", label: "ศาลเยาวชนและครอบครัวจังหวัดชลบุรี" },
  { value: "ccsc", label: "ศาลจังหวัดฉะเชิงเทรา" },
  { value: "ccsjc", label: "ศาลเยาวชนและครอบครัวจังหวัดฉะเชิงเทรา" },
  { value: "nknc", label: "ศาลจังหวัดนครนายก" },
  { value: "nknjc", label: "ศาลเยาวชนและครอบครัวจังหวัดนครนายก" },
  { value: "prbc", label: "ศาลจังหวัดปราจีนบุรี" },
  { value: "prbjc", label: "ศาลเยาวชนและครอบครัวจังหวัดปราจีนบุรี" },
  { value: "sakc", label: "ศาลจังหวัดสระแก้ว" },
  { value: "sakjc", label: "ศาลเยาวชนและครอบครัวจังหวัดสระแก้ว" },
  { value: "kbbc", label: "ศาลจังหวัดกบินทร์บุรี" },
  { value: "rayc", label: "ศาลจังหวัดระยอง" },
  { value: "rayjc", label: "ศาลเยาวชนและครอบครัวจังหวัดระยอง" },
  { value: "trtc", label: "ศาลจังหวัดตราด" },
  { value: "trtjc", label: "ศาลเยาวชนและครอบครัวจังหวัดตราด" },
  { value: "ctbc", label: "ศาลจังหวัดจันทบุรี" },
  { value: "ctbjc", label: "ศาลเยาวชนและครอบครัวจังหวัดจันทบุรี" },
  { value: "ptyc", label: "ศาลจังหวัดพัทยา" },
  { value: "lbchnc", label: "ศาลแรงงานภาค 2 (ชลบุรี)" },
  { value: "jor3", label: "สำนักงานอธิบดีผู้พิพากษาภาค 3" },
  { value: "nksc", label: "ศาลจังหวัดนครราชสีมา" },
  { value: "nksmc", label: "ศาลแขวงนครราชสีมา" },
  { value: "nksjc", label: "ศาลเยาวชนและครอบครัวจังหวัดนครราชสีมา" },
  { value: "byic", label: "ศาลจังหวัดบัวใหญ่" },
  { value: "skuc", label: "ศาลจังหวัดสีคิ้ว" },
  { value: "skupcc", label: "ศาลจังหวัดสีคิ้ว (ปากช่อง)" },
  { value: "cypc", label: "ศาลจังหวัดชัยภูมิ" },
  { value: "cypjc", label: "ศาลเยาวชนและครอบครัวจังหวัดชัยภูมิ" },
  { value: "pkwc", label: "ศาลจังหวัดภูเขียว" },
  { value: "brrc", label: "ศาลจังหวัดบุรีรัมย์" },
  { value: "brrjc", label: "ศาลเยาวชนและครอบครัวจังหวัดบุรีรัมย์" },
  { value: "nrgc", label: "ศาลจังหวัดนางรอง" },
  { value: "srnc", label: "ศาลจังหวัดสุรินทร์" },
  { value: "srnmc", label: "ศาลแขวงสุรินทร์" },
  { value: "srnjc", label: "ศาลเยาวชนและครอบครัวจังหวัดสุรินทร์" },
  { value: "rtbc", label: "ศาลจังหวัดรัตนบุรี" },
  { value: "sskc", label: "ศาลจังหวัดศรีสะเกษ" },
  { value: "sskjc", label: "ศาลเยาวชนและครอบครัวจังหวัดศรีสะเกษ" },
  { value: "ktlc", label: "ศาลจังหวัดกันทรลักษ์" },
  { value: "ubtc", label: "ศาลจังหวัดอุบลราชธานี" },
  { value: "ubtmc", label: "ศาลแขวงอุบลราชธานี" },
  { value: "ubtjc", label: "ศาลเยาวชนและครอบครัวจังหวัดอุบลราชธานี" },
  { value: "dudc", label: "ศาลจังหวัดเดชอุดม" },
  { value: "uncc", label: "ศาลจังหวัดอำนาจเจริญ" },
  { value: "uncjc", label: "ศาลเยาวชนและครอบครัวจังหวัดอำนาจเจริญ" },
  { value: "ystc", label: "ศาลจังหวัดยโสธร" },
  { value: "ystjc", label: "ศาลเยาวชนและครอบครัวจังหวัดยโสธร" },
  { value: "lbnksc", label: "ศาลแรงงานภาค 3 (นครราชสีมา)" },
  { value: "jor4", label: "สำนักงานอธิบดีผู้พิพากษาภาค 4" },
  { value: "kknc", label: "ศาลจังหวัดขอนแก่น" },
  { value: "kknmc", label: "ศาลแขวงขอนแก่น" },
  { value: "kknjc", label: "ศาลเยาวชนและครอบครัวจังหวัดขอนแก่น" },
  { value: "phnc", label: "ศาลจังหวัดพล" },
  { value: "udtc", label: "ศาลจังหวัดอุดรธานี" },
  { value: "udtmc", label: "ศาลแขวงอุดรธานี" },
  { value: "udtjc", label: "ศาลเยาวชนและครอบครัวจังหวัดอุดรธานี" },
  { value: "nnkc", label: "ศาลจังหวัดหนองคาย" },
  { value: "nnkjc", label: "ศาลเยาวชนและครอบครัวจังหวัดหนองคาย" },
  { value: "bngc", label: "ศาลจังหวัดบึงกาฬ" },
  { value: "leic", label: "ศาลจังหวัดเลย" },
  { value: "leijc", label: "ศาลเยาวชนและครอบครัวจังหวัดเลย" },
  { value: "sknc", label: "ศาลจังหวัดสกลนคร" },
  { value: "sknjc", label: "ศาลเยาวชนและครอบครัวจังหวัดสกลนคร" },
  { value: "swdc", label: "ศาลจังหวัดสว่างแดนดิน" },
  { value: "nkpc", label: "ศาลจังหวัดนครพนม" },
  { value: "nkpjc", label: "ศาลเยาวชนและครอบครัวจังหวัดนครพนม" },
  { value: "mdhc", label: "ศาลจังหวัดมุกดาหาร" },
  { value: "mdhjc", label: "ศาลเยาวชนและครอบครัวจังหวัดมุกดาหาร" },
  { value: "mhkc", label: "ศาลจังหวัดมหาสารคาม" },
  { value: "mhkjc", label: "ศาลเยาวชนและครอบครัวจังหวัดมหาสารคาม" },
  { value: "riec", label: "ศาลจังหวัดร้อยเอ็ด" },
  { value: "riejc", label: "ศาลเยาวชนและครอบครัวจังหวัดร้อยเอ็ด" },
  { value: "klsc", label: "ศาลจังหวัดกาฬสินธุ์" },
  { value: "klsjc", label: "ศาลเยาวชนและครอบครัวจังหวัดกาฬสินธุ์" },
  { value: "nblc", label: "ศาลจังหวัดหนองบัวลำภู" },
  { value: "nbljc", label: "ศาลเยาวชนและครอบครัวจังหวัดหนองบัวลำภู" },
  { value: "lbudtc", label: "ศาลแรงงานภาค 4 (อุดรธานี)" },
  { value: "jor5", label: "สำนักงานอธิบดีผู้พิพากษาภาค 5" },
  { value: "cmic", label: "ศาลจังหวัดเชียงใหม่" },
  { value: "cmimc", label: "ศาลแขวงเชียงใหม่" },
  { value: "cmijc", label: "ศาลเยาวชนและครอบครัวจังหวัดเชียงใหม่" },
  { value: "fngc", label: "ศาลจังหวัดฝาง" },
  { value: "lpgc", label: "ศาลจังหวัดลำปาง" },
  { value: "lpgmc", label: "ศาลแขวงลำปาง" },
  { value: "lpgjc", label: "ศาลเยาวชนและครอบครัวจังหวัดลำปาง" },
  { value: "mhsc", label: "ศาลจังหวัดแม่ฮ่องสอน" },
  { value: "mhsjc", label: "ศาลเยาวชนและครอบครัวจังหวัดแม่ฮ่องสอน" },
  { value: "msrc", label: "ศาลจังหวัดแม่สะเรียง" },
  { value: "cric", label: "ศาลจังหวัดเชียงราย" },
  { value: "crijc", label: "ศาลเยาวชนและครอบครัวจังหวัดเชียงราย" },
  { value: "pyoc", label: "ศาลจังหวัดพะเยา" },
  { value: "pyojc", label: "ศาลเยาวชนและครอบครัวจังหวัดพะเยา" },
  { value: "nanc", label: "ศาลจังหวัดน่าน" },
  { value: "nanjc", label: "ศาลเยาวชนและครอบครัวจังหวัดน่าน" },
  { value: "lpnc", label: "ศาลจังหวัดลำพูน" },
  { value: "lpnjc", label: "ศาลเยาวชนและครอบครัวจังหวัดลำพูน" },
  { value: "prec", label: "ศาลจังหวัดแพร่" },
  { value: "prejc", label: "ศาลเยาวชนและครอบครัวจังหวัดแพร่" },
  { value: "tngc", label: "ศาลจังหวัดเทิง" },
  { value: "lbcmic", label: "ศาลแรงงานภาค 5 (เชียงใหม่)" },
  { value: "jor6", label: "สำนักงานอธิบดีผู้พิพากษาภาค 6" },
  { value: "pslc", label: "ศาลจังหวัดพิษณุโลก" },
  { value: "pslmc", label: "ศาลแขวงพิษณุโลก" },
  { value: "psljc", label: "ศาลเยาวชนและครอบครัวจังหวัดพิษณุโลก" },
  { value: "sktc", label: "ศาลจังหวัดสุโขทัย" },
  { value: "sktjc", label: "ศาลเยาวชนและครอบครัวจังหวัดสุโขทัย" },
  { value: "swlc", label: "ศาลจังหวัดสวรรคโลก" },
  { value: "utdc", label: "ศาลจังหวัดอุตรดิตถ์" },
  { value: "utdjc", label: "ศาลเยาวชนและครอบครัวจังหวัดอุตรดิตถ์" },
  { value: "takc", label: "ศาลจังหวัดตาก" },
  { value: "takjc", label: "ศาลเยาวชนและครอบครัวจังหวัดตาก" },
  { value: "mesc", label: "ศาลจังหวัดแม่สอด" },
  { value: "kppc", label: "ศาลจังหวัดกำแพงเพชร" },
  { value: "kppjc", label: "ศาลเยาวชนและครอบครัวจังหวัดกำแพงเพชร" },
  { value: "phcc", label: "ศาลจังหวัดพิจิตร" },
  { value: "phcjc", label: "ศาลเยาวชนและครอบครัวจังหวัดพิจิตร" },
  { value: "pcbc", label: "ศาลจังหวัดเพชรบูรณ์" },
  { value: "pcbjc", label: "ศาลเยาวชนและครอบครัวจังหวัดเพชรบูรณ์" },
  { value: "lskc", label: "ศาลจังหวัดหล่มสัก" },
  { value: "nkwc", label: "ศาลจังหวัดนครสวรรค์" },
  { value: "nkwmc", label: "ศาลแขวงนครสวรรค์" },
  { value: "nkwjc", label: "ศาลเยาวชนและครอบครัวจังหวัดนครสวรรค์" },
  { value: "uttc", label: "ศาลจังหวัดอุทัยธานี" },
  { value: "uttjc", label: "ศาลเยาวชนและครอบครัวจังหวัดอุทัยธานี" },
  { value: "lbnkwc", label: "ศาลแรงงานภาค 6 (นครสวรรค์)" },
  { value: "jor7", label: "สำนักงานอธิบดีผู้พิพากษาภาค 7" },
  { value: "nktc", label: "ศาลจังหวัดนครปฐม" },
  { value: "nktmc", label: "ศาลแขวงนครปฐม" },
  { value: "nktjc", label: "ศาลเยาวชนและครอบครัวจังหวัดนครปฐม" },
  { value: "rcbc", label: "ศาลจังหวัดราชบุรี" },
  { value: "rcbmc", label: "ศาลแขวงราชบุรี" },
  { value: "rcbjc", label: "ศาลเยาวชนและครอบครัวจังหวัดราชบุรี" },
  { value: "spbc", label: "ศาลจังหวัดสุพรรณบุรี" },
  { value: "spbmc", label: "ศาลแขวงสุพรรณบุรี" },
  { value: "spbjc", label: "ศาลเยาวชนและครอบครัวจังหวัดสุพรรณบุรี" },
  { value: "kcbc", label: "ศาลจังหวัดกาญจนบุรี" },
  { value: "kcbjc", label: "ศาลเยาวชนและครอบครัวจังหวัดกาญจนบุรี" },
  { value: "tppc", label: "ศาลจังหวัดทองผาภูมิ" },
  { value: "pcrc", label: "ศาลจังหวัดเพชรบุรี" },
  { value: "pcrjc", label: "ศาลเยาวชนและครอบครัวจังหวัดเพชรบุรี" },
  { value: "pkkc", label: "ศาลจังหวัดประจวบคีรีขันธ์" },
  { value: "pkkjc", label: "ศาลเยาวชนและครอบครัวจังหวัดประจวบคีรีขันธ์" },
  { value: "smsc", label: "ศาลจังหวัดสมุทรสาคร" },
  { value: "smsjc", label: "ศาลเยาวชนและครอบครัวจังหวัดสมุทรสาคร" },
  { value: "smkc", label: "ศาลจังหวัดสมุทรสงคราม" },
  { value: "smkjc", label: "ศาลเยาวชนและครอบครัวจังหวัดสมุทรสงคราม" },
  { value: "lbkcbc", label: "ศาลแรงงานภาค 7 (สมุทรสงคราม)" },
  { value: "jor8", label: "สำนักงานอธิบดีผู้พิพากษาภาค 8" },
  { value: "srtc", label: "ศาลจังหวัดสุราษฎร์ธานี" },
  { value: "srtmc", label: "ศาลแขวงสุราษฎร์ธานี" },
  { value: "srtjc", label: "ศาลเยาวชนและครอบครัวจังหวัดสุราษฎร์ธานี" },
  { value: "smc", label: "ศาลจังหวัดเกาะสมุย" },
  { value: "cyac", label: "ศาลจังหวัดไชยา" },
  { value: "nstc", label: "ศาลจังหวัดนครศรีธรรมราช" },
  { value: "nstmc", label: "ศาลแขวงนครศรีธรรมราช" },
  { value: "nstjc", label: "ศาลเยาวชนและครอบครัวจังหวัดนครศรีธรรมราช" },
  { value: "ppnc", label: "ศาลจังหวัดปากพนัง" },
  { value: "tnsc", label: "ศาลจังหวัดทุ่งสง" },
  { value: "cmpc", label: "ศาลจังหวัดชุมพร" },
  { value: "cmpjc", label: "ศาลเยาวชนและครอบครัวจังหวัดชุมพร" },
  { value: "lnsc", label: "ศาลจังหวัดหลังสวน" },
  { value: "rnnc", label: "ศาลจังหวัดระนอง" },
  { value: "rnnjc", label: "ศาลเยาวชนและครอบครัวจังหวัดระนอง" },
  { value: "krbc", label: "ศาลจังหวัดกระบี่" },
  { value: "krbjc", label: "ศาลเยาวชนและครอบครัวจังหวัดกระบี่" },
  { value: "pngc", label: "ศาลจังหวัดพังงา" },
  { value: "pngjc", label: "ศาลเยาวชนและครอบครัวจังหวัดพังงา" },
  { value: "tkpc", label: "ศาลจังหวัดตะกั่วป่า" },
  { value: "phkc", label: "ศาลจังหวัดภูเก็ต" },
  { value: "phkjc", label: "ศาลเยาวชนและครอบครัวจังหวัดภูเก็ต" },
  { value: "lbphkc", label: "ศาลแรงงานภาค 8 (ภูเก็ต)" },
  { value: "jor9", label: "สำนักงานอธิบดีผู้พิพากษาภาค 9" },
  { value: "sklc", label: "ศาลจังหวัดสงขลา" },
  { value: "sklmc", label: "ศาลแขวงสงขลา" },
  { value: "skljc", label: "ศาลเยาวชนและครอบครัวจังหวัดสงขลา" },
  { value: "ntvc", label: "ศาลจังหวัดนาทวี" },
  { value: "trnc", label: "ศาลจังหวัดตรัง" },
  { value: "trnjc", label: "ศาลเยาวชนและครอบครัวจังหวัดตรัง" },
  { value: "ptlc", label: "ศาลจังหวัดพัทลุง" },
  { value: "ptljc", label: "ศาลเยาวชนและครอบครัวจังหวัดพัทลุง" },
  { value: "stnc", label: "ศาลจังหวัดสตูล" },
  { value: "stnjc", label: "ศาลเยาวชนและครอบครัวจังหวัดสตูล" },
  { value: "ptnc", label: "ศาลจังหวัดปัตตานี" },
  { value: "ptnjc", label: "ศาลเยาวชนและครอบครัวจังหวัดปัตตานี" },
  { value: "ylac", label: "ศาลจังหวัดยะลา" },
  { value: "ylajc", label: "ศาลเยาวชนและครอบครัวจังหวัดยะลา" },
  { value: "btnc", label: "ศาลจังหวัดเบตง" },
  { value: "nrtc", label: "ศาลจังหวัดนราธิวาส" },
  { value: "nrtjc", label: "ศาลเยาวชนและครอบครัวจังหวัดนราธิวาส" },
  { value: "lbsklc", label: "ศาลแรงงานภาค 9 (สงขลา)" },
  { value: "mnbjc", label: "ศาลเยาวชนและครอบครัวกลาง (สาขามีนบุรี) กำลังจะปิดบริการ" },
  { value: "bngjc", label: "ศาลเยาวชนและครอบครัวจังหวัดบึงกาฬ" },
  { value: "wsc", label: "ศาลจังหวัดเวียงสระ" },
  { value: "hhc", label: "ศาลจังหวัดหัวหิน" },
  { value: "wcbc", label: "ศาลจังหวัดวิเชียรบุรี" },
  { value: "phmc", label: "ศาลจังหวัดพิมาย" },
  { value: "dmmc", label: "ศาลแขวงดอนเมือง" },
  { value: "srbmc", label: "ศาลแขวงสระบุรี" },
  { value: "ptymc", label: "ศาลแขวงพัทยา" },
  { value: "wppmc", label: "ศาลแขวงเวียงป่าเป้า" },
  { value: "hodc", label: "ศาลจังหวัดฮอด" },
  { value: "ntmc", label: "ศาลแขวงนครไทย" },
  { value: "tnsmc", label: "ศาลแขวงทุ่งสง" },
  { value: "pypmc", label: "ศาลแขวงพยัคฆภูมิพิสัย" },
  { value: "cphc", label: "ศาลจังหวัดชุมแพ" },
  { value: "cccm", label: "ศาลอาญาคดีทุจริตและประพฤติมิชอบกลาง" },
  { value: "chkc", label: "ศาลจังหวัดเชียงคำ" },
  { value: "cccm1", label: "ศาลอาญาคดีทุจริตและประพฤติมิชอบภาค 1" },
  { value: "cccm3", label: "ศาลอาญาคดีทุจริตและประพฤติมิชอบภาค 3" },
  { value: "cccm4", label: "ศาลอาญาคดีทุจริตและประพฤติมิชอบภาค 4" },
  { value: "cccm5", label: "ศาลอาญาคดีทุจริตและประพฤติมิชอบภาค 5" },
  { value: "cccm6", label: "ศาลอาญาคดีทุจริตและประพฤติมิชอบภาค 6" },
  { value: "cccm8", label: "ศาลอาญาคดีทุจริตและประพฤติมิชอบภาค 8" },
  { value: "cccm9", label: "ศาลอาญาคดีทุจริตและประพฤติมิชอบภาค 9" },
  { value: "cccm2", label: "ศาลอาญาคดีทุจริตและประพฤติมิชอบภาค 2" },
  { value: "cccm7", label: "ศาลอาญาคดีทุจริตและประพฤติมิชอบภาค 7" },
  { value: "phkmc", label: "ศาลแขวงภูเก็ต" },
  { value: "pslc_nt", label: "ศาลจังหวัดพิษณุโลก (สาขานครไทย)" },
  { value: "cric_wpp", label: "ศาลจังหวัดเชียงราย (สาขาเวียงป่าเป้า)" },
  { value: "mhkc_pyp", label: "ศาลจังหวัดมหาสารคาม (สาขาพยัคฆภูมิพิสัย)" },
  { value: "lblbrc-ayuttaya", label: "ศาลแรงงานภาค 1 (สระบุรี) สาขาพระนครศรีอยุธยา" },
  { value: "raymc", label: "ศาลแขวงระยอง" },
  { value: "nanpc", label: "ศาลจังหวัดน่าน (สาขาปัว)" },
  { value: "mhspc", label: "ศาลจังหวัดแม่ฮ่องสอน (สาขาปาย)" },
  { value: "bbmc", label: "ศาลแขวงบางบอน" },
  { value: "crmc", label: "ศาลแขวงเชียงราย" },
  { value: "lbchnc-ray", label: "ศาลแรงงานภาค 2 (ชลบุรี) สาขาระยอง" },
  { value: "mesc_takjc", label: "ศาลเยาวชนและครอบครัวจังหวัดตาก(แม่สอด)" },
  { value: "civiltlc", label: "ศาลแพ่งตลิ่งชัน" },
  { value: "crimtlc", label: "ศาลอาญาตลิ่งชัน" },
  { value: "civilpkc", label: "ศาลแพ่งพระโขนง" },
  { value: "crimpkc", label: "ศาลอาญาพระโขนง" },
  { value: "civilmbc", label: "ศาลแพ่งมีนบุรี" },
  { value: "crimmbc", label: "ศาลอาญามีนบุรี" },
  { value: "ylajc_bt", label: "ศาลเยาวชนและครอบครัวจังหวัดยะลา (เบตง)" },
  { value: "cmijc_fng", label: "ศาลเยาวชนและครอบครัวจังหวัดเชียงใหม่ (ฝาง)" },
  { value: "kcbjc_tpp", label: "ศาลเยาวชนและครอบครัวจังหวัดกาญจนบุรี (ทองผาภูมิ)" },
  { value: "srtjc_sm", label: "ศาลเยาวชนและครอบครัวจังหวัดสุราษฎร์ธานี (เกาะสมุย)" },
  { value: "pngjc_tkc", label: "ศาลเยาวชนและครอบครัวจังหวัดพังงา (ตะกั่วป่า)" },
  { value: "cdmc", label: "ศาลแขวงเชียงดาว" },
  { value: "krbmc", label: "ศาลแขวงกระบี่" },
  { value: "trnmc", label: "ศาลแขวงตรัง" },
  { value: "tbmc.coj", label: "ศูนย์ TBMC" },
  { value: "ppdc", label: "ศาลจังหวัดพระประแดง" },
  { value: "ccmbjc", label: "ศาลแพ่งมีนบุรีและศาลอาญามีนบุรีแผนกคดีเยาวชนและครอบครัว" },
  { value: "swpkc", label: "ศาลแขวงสุวรรณภูมิ" },
  { value: "riec_swp", label: "ศาลจังหวัดร้อยเอ็ด (สาขาสุวรรณภูมิ)" },
];
